name: libav

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nasm
      run: |
        sudo apt-get install nasm
    - name: Install libav
      run: |
        git clone --depth 1 https://github.com/libav/libav
        cd libav
        ./configure --prefix=$HOME/libav_dir
        make
        make install
    - name: Run tests
      run: |
        export PKG_CONFIG_PATH=$HOME/libav_dir/lib/pkgconfig:$PKG_CONFIG_PATH
        cargo test --all-features
